# Generated by Django 2.2.6 on 2020-02-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_for_real_test', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Feature Questions',
            },
        ),
        migrations.CreateModel(
            name='Stimuli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimuli_1', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_2', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_3', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_4', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_5', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_6', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_7', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_8', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_9', models.ImageField(default='Contrast00.png', upload_to='images/')),
                ('stimuli_10', models.ImageField(default='Contrast00.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Stimuli',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('question_attended', models.ManyToManyField(to='AllTogether.Question')),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='UserResponsesForFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='Feature_1')),
                ('choice_2', models.BooleanField(default=False, verbose_name='Feature_2')),
                ('choice_3', models.BooleanField(default=False, verbose_name='Feature_3')),
                ('choice_4', models.BooleanField(default=False, verbose_name='Feature_4')),
                ('choice_5', models.BooleanField(default=False, verbose_name='Feature_5')),
                ('choice_corr', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.QuestionFeatures')),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for features',
            },
        ),
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='sample1_A')),
                ('choice_2', models.BooleanField(default=False, verbose_name='sample2_A')),
                ('choice_3', models.BooleanField(default=False, verbose_name='sample3_A')),
                ('choice_4', models.BooleanField(default=False, verbose_name='sample4_A')),
                ('choice_5', models.BooleanField(default=False, verbose_name='sample5_A')),
                ('choice_6', models.BooleanField(default=False, verbose_name='sample6_A')),
                ('choice_7', models.BooleanField(default=False, verbose_name='sample7_A')),
                ('choice_8', models.BooleanField(default=False, verbose_name='sample8_A')),
                ('choice_9', models.BooleanField(default=False, verbose_name='sample9_A')),
                ('choice_10', models.BooleanField(default=False, verbose_name='sample10_A')),
                ('iteration', models.IntegerField(default=1)),
                ('choice_corr', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllTogether.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.QuestionFeatures')),
            ],
            options={
                'verbose_name_plural': 'Feature Choice',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1_A', models.ImageField(upload_to='images/')),
                ('sample2_A', models.ImageField(upload_to='images/')),
                ('sample3_A', models.ImageField(upload_to='images/')),
                ('sample4_A', models.ImageField(upload_to='images/')),
                ('sample5_A', models.ImageField(upload_to='images/')),
                ('sample6_A', models.ImageField(upload_to='images/')),
                ('sample7_A', models.ImageField(upload_to='images/')),
                ('sample8_A', models.ImageField(upload_to='images/')),
                ('sample9_A', models.ImageField(upload_to='images/')),
                ('sample10_A', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.Question')),
            ],
            options={
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
