# Generated by Django 2.2.6 on 2020-02-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
