# Generated by Django 2.2.6 on 2020-02-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0002_userdetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponsesforfeatures',
            name='choice_6',
            field=models.BooleanField(default=False, verbose_name='Color for classification'),
        ),
        migrations.AddField(
            model_name='userresponsesforfeatures',
            name='choice_7',
            field=models.BooleanField(default=False, verbose_name='None of the above'),
        ),
    ]
