# Generated by Django 2.2.6 on 2020-02-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0003_auto_20200210_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_1',
            field=models.BooleanField(default=False, verbose_name='Lower Fin'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_2',
            field=models.BooleanField(default=False, verbose_name='Tail'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_3',
            field=models.BooleanField(default=False, verbose_name='Upper Fin'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_4',
            field=models.BooleanField(default=False, verbose_name='Body FIn'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_5',
            field=models.BooleanField(default=False, verbose_name='Mouth'),
        ),
        migrations.CreateModel(
            name='UserResponsesForDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='AllTogether.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for Description',
            },
        ),
    ]
