# Generated by Django 2.2.6 on 2020-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0006_auto_20200210_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfeatures',
            name='question_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeatures',
            name='choice_4',
            field=models.BooleanField(default=False, verbose_name='Body Fin'),
        ),
    ]
